name: Auto Update

on:
  schedule:
    - cron: '0 0 * * *'   # Runs every hour, adjust as needed
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update last-updated.txt
        run: |
          echo "$(date -u)" > last-updated.txt

      - name: Commit changes
        run: |
          git add last-updated.txt
          git commit -m "Auto update $(date -u)" || echo "No changes to commit"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ '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' }}
        run: |
          git push https://x-access-token:${PAT_TOKEN}@github.com/noushad970/PSTU-CSE-2019.git HEAD:main
